version: '3.1'

services:
  codrr_pg:
    image: postgres:15.1
    container_name: taskr_pg
    restart: always
    environment:
      POSTGRES_DB: taskrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
